# Use an official .NET runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 5001

# Use an official .NET SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies
COPY ["club.csproj", "./"]
RUN dotnet restore "./club.csproj"

# Copy the entire project and build the app
COPY . .
RUN dotnet publish -c Release -o /app/publish

# Final runtime image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

# Copy the SSL certificate
COPY certs/aspnetapp.pfx /https/aspnetapp.pfx

ENTRYPOINT ["dotnet", "club.dll"]

